import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/Styles/globals.css";

//import craft
import { Layout, Main } from "@/components/craft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Layout>
      <body className={inter.className}>
        <Main>{children}</Main>
      </body>
    </Layout>
  );
}
